using ClarityBelongs.Web.Domain;
using System.Text.Json;

namespace ClarityBelongs.Web.Services;

public sealed record ClarityProduct(
    string Slug,
    string Name,
    string ShortDescription,
    string Outcome,
    string TargetLabel,
    string TargetPlaceholder,
    string TargetType,
    string MonitorType,
    string AdapterType,
    string SourceConfigurationJson,
    int DefaultCadenceMinutes,
    string DefaultImportance,
    string DefaultAlertRule,
    string HelpText,
    string Family = "Your Internet");

public sealed class ClarityProductCatalog
{
    private static readonly IReadOnlyList<ClarityProduct> Products =
    [
        Web(
            "product-price",
            "Product Price Monitor",
            "Money",
            "Know when a public product or pricing page changes.",
            "Clarity keeps before/after pricing-page evidence so you can review published price changes over time.",
            "Product or pricing page URL",
            "https://example.com/product",
            360,
            "Normal",
            "V1 watches the public source page rather than claiming universal structured price extraction."),
        Web(
            "restock-availability",
            "Restock & Availability Monitor",
            "Money",
            "Know when a public product or availability page changes.",
            "Clarity keeps the page history so restocks, availability changes, or listing updates are easier to catch.",
            "Product or availability page URL",
            "https://example.com/product",
            60,
            "Normal",
            "V1 watches the public page itself and does not bypass retailer controls."),
        Web(
            "subscription-price-change",
            "Subscription Price Change Monitor",
            "Money",
            "Follow a public subscription pricing page for changes.",
            "Clarity preserves old and new versions so plan, fee, and published pricing changes remain visible.",
            "Subscription pricing page URL",
            "https://example.com/pricing",
            720,
            "Normal",
            "Use the provider's public pricing or plan page."),
        Web(
            "airfare",
            "Airfare Monitor",
            "Money",
            "Follow a public fare or itinerary result page for changes.",
            "Clarity records changes to the public fare source you choose instead of making you repeatedly reopen it.",
            "Public fare page URL",
            "https://example.com/flights",
            60,
            "Normal",
            "V1 is source-page monitoring. It does not bypass airline controls or promise access to private fare APIs."),
        Web(
            "hotel-rate",
            "Hotel Rate Monitor",
            "Money",
            "Follow a public hotel rate or booking page for changes.",
            "Clarity keeps a history of the public rate source so changes are easier to review.",
            "Hotel rate page URL",
            "https://example.com/hotel",
            360,
            "Normal",
            "Use a stable public hotel or booking page."),
        Web(
            "rental-car-rate",
            "Rental Car Rate Monitor",
            "Money",
            "Follow a public rental-car rate page for changes.",
            "Clarity records the public source over time so rate or availability changes remain visible.",
            "Rental-car page URL",
            "https://example.com/cars",
            360,
            "Normal",
            "Use a stable public rental-car result or provider page."),
        Web(
            "event-ticket-price",
            "Event Ticket Price Monitor",
            "Money",
            "Follow a public event-ticket page for price or availability changes.",
            "Clarity preserves page history and surfaces changes to the public ticket source.",
            "Ticket page URL",
            "https://example.com/event",
            60,
            "Normal",
            "V1 watches a public ticket page and does not bypass queues, logins, or anti-bot controls."),
        Web(
            "fee-change",
            "Fee Change Monitor",
            "Money",
            "Track public pages that publish fees, rates, or charges.",
            "Clarity keeps before/after evidence when the published fee page changes.",
            "Fee or rate page URL",
            "https://example.com/fees",
            720,
            "Normal",
            "Useful for banks, utilities, memberships, subscriptions, and government fee schedules."),
        Web(
            "sale-price-history",
            "Price & Sale History Monitor",
            "Money",
            "Keep a change history for a public pricing or product page.",
            "Clarity preserves page snapshots so current sale language and published prices can be compared with earlier versions.",
            "Pricing or product page URL",
            "https://example.com/product",
            360,
            "Normal",
            "V1 records page evidence rather than claiming a universal retailer price database."),

        Uptime(
            "website-uptime",
            "Website Uptime Monitor",
            "Your Internet",
            "Know when a website stops responding or recovers.",
            "Clarity records HTTP availability transitions without treating ordinary response-time variation as a content change.",
            "Website URL",
            "https://example.com",
            5,
            "High",
            "Use this for public websites and endpoints where availability matters."),
        Tls(
            "ssl-expiration",
            "SSL Expiration Monitor",
            "Your Internet",
            "Track certificate identity and expiration.",
            "Clarity records the public certificate and makes certificate changes and expiration state visible.",
            "HTTPS site or host",
            "https://example.com",
            720,
            "High",
            "Expiration reminders use the shared Clarity notification engine."),
        Domain(
            "domain-expiration",
            "Domain Expiration Monitor",
            "Your Internet",
            "Track the expiration date published by the domain registry.",
            "Clarity uses RDAP data to keep domain registration expiration visible.",
            "Domain",
            "example.com",
            1440,
            "High",
            "Registry data availability varies by TLD."),
        DnsAddress(
            "dns-change",
            "DNS Change Monitor",
            "Your Internet",
            "Know when a hostname starts resolving somewhere different.",
            "Clarity stores the normalized public address set and reports changes.",
            "Hostname",
            "example.com",
            60,
            "High",
            "V1 observes the public IP address set returned by DNS."),
        DnsRecord(
            "nameserver-change",
            "Nameserver Change Monitor",
            "Your Internet",
            "Know when a domain's public nameserver set changes.",
            "Clarity records normalized NS answers and surfaces differences.",
            "Domain",
            "example.com",
            "NS",
            360,
            "High"),
        Uptime(
            "http-status",
            "HTTP Status Monitor",
            "Your Internet",
            "Track the public HTTP result returned by a URL.",
            "Clarity records the final URL and HTTP status so availability-state changes remain visible.",
            "Public URL",
            "https://example.com/health",
            15,
            "High",
            "Useful for health pages, public endpoints, and exact URLs where the returned status matters."),
        Uptime(
            "redirect-chain",
            "Redirect Destination Monitor",
            "Your Internet",
            "Know when a public URL starts resolving to a different final destination.",
            "Clarity follows a bounded redirect chain and records the final public URL and status.",
            "Starting URL",
            "https://example.com/old-page",
            60,
            "Normal",
            "V1 records the final destination after up to three redirects."),
        Uptime(
            "broken-link",
            "Broken Link Monitor",
            "Your Internet",
            "Watch a specific public link and know when it stops working or recovers.",
            "Clarity records the HTTP availability state of the exact link you provide.",
            "Link URL",
            "https://example.com/important-page",
            60,
            "Normal",
            "V1 checks one specific public link per follow rather than crawling an entire site."),
        Web(
            "sitemap-change",
            "Sitemap Change Monitor",
            "Your Internet",
            "Know when a public sitemap changes.",
            "Clarity keeps sitemap snapshots and before/after evidence.",
            "Sitemap URL",
            "https://example.com/sitemap.xml",
            360,
            "Normal",
            "Use the public XML sitemap URL you care about."),
        Web(
            "robots-change",
            "Robots.txt Change Monitor",
            "Your Internet",
            "Know when a site's public crawler instructions change.",
            "Clarity records robots.txt history and surfaces differences.",
            "Robots.txt URL",
            "https://example.com/robots.txt",
            360,
            "Normal",
            "Use the site's public robots.txt URL."),
        DnsRecord(
            "mx-record",
            "MX Record Monitor",
            "Your Internet",
            "Know when a domain's mail-exchanger records change.",
            "Clarity records normalized MX answers and surfaces differences.",
            "Domain",
            "example.com",
            "MX",
            360,
            "High"),
        DnsRecord(
            "spf-record",
            "SPF Record Monitor",
            "Your Internet",
            "Know when a domain's published TXT records used for SPF change.",
            "Clarity stores normalized TXT answers so SPF-related DNS changes remain visible.",
            "Domain",
            "example.com",
            "TXT",
            360,
            "High"),
        DnsRecord(
            "dkim-record",
            "DKIM Record Monitor",
            "Your Internet",
            "Know when a selected DKIM TXT record changes.",
            "Clarity stores the normalized TXT answer for the selector hostname you provide.",
            "DKIM selector hostname",
            "selector._domainkey.example.com",
            "TXT",
            360,
            "High"),
        DnsRecord(
            "dmarc-record",
            "DMARC Record Monitor",
            "Your Internet",
            "Know when a domain's DMARC TXT record changes.",
            "Clarity stores normalized TXT answers for the _dmarc hostname.",
            "DMARC hostname",
            "_dmarc.example.com",
            "TXT",
            360,
            "High"),
        Web(
            "ip-blacklist",
            "IP Blacklist Report Monitor",
            "Your Internet",
            "Follow a public blacklist or reputation report page for changes.",
            "Clarity preserves the public report history so status changes are easier to catch.",
            "Public blacklist report URL",
            "https://example.com/report",
            360,
            "High",
            "V1 follows the public report URL you choose; Clarity does not claim a proprietary blacklist database."),
        Web(
            "website-malware-reputation",
            "Website Malware Reputation Monitor",
            "Your Internet",
            "Follow a public security or reputation report for changes.",
            "Clarity keeps before/after evidence from the public report source you provide.",
            "Public security report URL",
            "https://example.com/report",
            360,
            "High",
            "V1 monitors a public report page rather than performing antivirus scanning itself."),
        Web(
            "page-speed-regression",
            "Page Speed Report Monitor",
            "Your Internet",
            "Follow a public page-speed report for changes.",
            "Clarity preserves report-page history so regressions or improvements can be reviewed over time.",
            "Public performance report URL",
            "https://example.com/report",
            720,
            "Normal",
            "V1 monitors the public report source you choose rather than running a browser lab itself."),
        Web(
            "core-web-vitals",
            "Core Web Vitals Report Monitor",
            "Your Internet",
            "Follow a public Core Web Vitals or performance report for changes.",
            "Clarity keeps report-page history and surfaces changed evidence.",
            "Public Core Web Vitals report URL",
            "https://example.com/report",
            720,
            "Normal",
            "V1 follows a public report page; a dedicated browser-performance adapter can be added later if usage justifies it."),

        Web(
            "website-change",
            "Website Change Monitor",
            "Changes",
            "Know when the content of a public webpage changes.",
            "Clarity keeps a history of the page and surfaces meaningful before/after changes.",
            "Webpage URL",
            "https://example.com/pricing",
            60,
            "Normal",
            "Best for pricing pages, policies, product pages, notices, and other pages you would otherwise revisit manually."),
        Web(
            "website-keyword-source",
            "Website Keyword Source Monitor",
            "Changes",
            "Follow a public page containing a keyword, phrase, or subject you care about.",
            "Clarity records page changes so you can review whether the watched subject changed in the source.",
            "Source page URL",
            "https://example.com/notices",
            60,
            "Normal",
            "V1 watches the source page as evidence; isolated keyword extraction is a later refinement."),
        Web(
            "competitor-pricing",
            "Competitor Pricing Monitor",
            "Changes",
            "Follow a competitor's public pricing page for changes.",
            "Clarity keeps before/after pricing-page evidence without requiring manual revisits.",
            "Competitor pricing URL",
            "https://example.com/pricing",
            360,
            "Normal",
            "Use only public pages you are permitted to access."),
        Web(
            "competitor-homepage",
            "Competitor Homepage Monitor",
            "Changes",
            "Know when a competitor's public homepage changes.",
            "Clarity preserves page history and surfaces changed public messaging or content.",
            "Competitor homepage URL",
            "https://example.com",
            360,
            "Normal",
            "Use only public pages you are permitted to access."),
        Web(
            "terms-change",
            "Terms of Service Change Monitor",
            "Changes",
            "Know when public terms of service change.",
            "Clarity preserves before/after evidence so changes are reviewable later.",
            "Terms page URL",
            "https://example.com/terms",
            720,
            "High",
            "Use the provider's public terms page."),
        Web(
            "privacy-policy-change",
            "Privacy Policy Change Monitor",
            "Changes",
            "Know when a public privacy policy changes.",
            "Clarity preserves before/after evidence so policy changes remain visible.",
            "Privacy policy URL",
            "https://example.com/privacy",
            720,
            "High",
            "Use the provider's public privacy-policy page."),
        Web(
            "app-store-rating",
            "App Store Rating Page Monitor",
            "Changes",
            "Follow a public app-store listing for rating or review-summary changes.",
            "Clarity keeps the listing-page history so public rating-state changes can be reviewed.",
            "Public app listing URL",
            "https://example.com/app",
            720,
            "Normal",
            "V1 monitors the public listing page rather than using a private app-store API."),
        Web(
            "app-store-release",
            "App Store Release Monitor",
            "Changes",
            "Follow a public app-store listing for release changes.",
            "Clarity keeps listing history so version or release-note changes are easier to catch.",
            "Public app listing URL",
            "https://example.com/app",
            360,
            "Normal",
            "Use the public listing page that publishes version information."),
        Web(
            "software-release",
            "Software Release Monitor",
            "Changes",
            "Follow a public software release or downloads page for changes.",
            "Clarity records the release source so new versions and release notes are easier to catch.",
            "Release page URL",
            "https://example.com/releases",
            360,
            "Normal",
            "Use the publisher's public release, download, or changelog page."),
        Web(
            "github-release",
            "GitHub Repository Release Monitor",
            "Changes",
            "Follow a repository's public releases page for changes.",
            "Clarity keeps release-page history so new public releases are easier to catch.",
            "GitHub releases URL",
            "https://github.com/owner/repo/releases",
            60,
            "Normal",
            "V1 uses the public releases page and does not require repository credentials."),
        Web(
            "package-release",
            "Package Dependency Release Monitor",
            "Changes",
            "Follow a public package-registry page for release changes.",
            "Clarity keeps the package page history so new versions are easier to notice.",
            "Package page URL",
            "https://www.nuget.org/packages/example",
            360,
            "Normal",
            "Works with a stable public package page from NuGet, npm, PyPI, or another registry."),
        Web(
            "public-status-page",
            "Public Status Page Monitor",
            "Changes",
            "Follow a public service status page for incident or recovery changes.",
            "Clarity preserves the status-page history and surfaces changed public incident information.",
            "Status page URL",
            "https://status.example.com",
            15,
            "High",
            "Useful when the status page itself is the authoritative public source."),
        Uptime(
            "service-outage",
            "Service Outage Monitor",
            "Changes",
            "Know when a public service endpoint stops responding or recovers.",
            "Clarity records availability transitions and recovery history for the public endpoint you follow.",
            "Service or status URL",
            "https://status.example.com",
            5,
            "High",
            "V1 observes public HTTP availability and does not infer outages from private account data."),
        Web(
            "cancellation-change",
            "Cancellation & Change Monitor",
            "Changes",
            "Follow a public schedule, event, travel, appointment, or meeting page for changes.",
            "Clarity records page history so changed dates and cancellation notices are easier to catch.",
            "Schedule or event page URL",
            "https://example.com/event",
            60,
            "High",
            "Choose the official public page most likely to publish the change you care about."),

        Web(
            "job-posting",
            "Job Posting Monitor",
            "Opportunities",
            "Follow a public jobs or search-results page for new or changed postings.",
            "Clarity preserves the source history so opportunity changes are easier to notice.",
            "Public jobs page URL",
            "https://example.com/jobs",
            360,
            "Normal",
            "Use a stable public employer, board, or search-results page."),
        Web(
            "grant-opportunity",
            "Grant Opportunity Monitor",
            "Opportunities",
            "Follow a public grants page for new or changed opportunities.",
            "Clarity records the public source and surfaces changes over time.",
            "Grant page URL",
            "https://example.gov/grants",
            360,
            "Normal",
            "Use the authoritative public grant source when possible."),
        Web(
            "government-bid",
            "Government Bid Monitor",
            "Opportunities",
            "Follow a public procurement or bid page for changes.",
            "Clarity keeps source history so new solicitations, amendments, or date changes are easier to catch.",
            "Bid or procurement page URL",
            "https://example.gov/bids",
            360,
            "Normal",
            "Use the authoritative public procurement source when possible."),
        Web(
            "new-listing",
            "New Listing & Availability Monitor",
            "Opportunities",
            "Follow a public listings page for additions or availability changes.",
            "Clarity preserves page history and surfaces changed listings.",
            "Public listings URL",
            "https://example.com/listings",
            60,
            "Normal",
            "Useful for public inventory, housing, marketplace, directory, or availability pages."),
        Web(
            "deadline-change",
            "Deadline Monitor",
            "Opportunities",
            "Follow a public application, registration, benefit, grant, or filing deadline page.",
            "Clarity keeps the source history so newly published or changed deadlines are easier to notice.",
            "Deadline page URL",
            "https://example.gov/deadlines",
            360,
            "High",
            "Always verify important deadlines with the authoritative source before relying on them."),

        Web(
            "public-meeting-agenda",
            "Public Meeting Agenda Monitor",
            "Public Information",
            "Follow a public meeting or agenda page for changes.",
            "Clarity keeps agenda-page history so additions, removals, and revisions are easier to catch.",
            "Meeting or agenda page URL",
            "https://example.gov/agendas",
            360,
            "Normal",
            "Use the official public body or agenda source when possible."),
        Web(
            "regulatory-filing",
            "Regulatory Filing Monitor",
            "Public Information",
            "Follow a public filings page for additions or changes.",
            "Clarity preserves the source history so newly published filings are easier to notice.",
            "Public filings page URL",
            "https://example.gov/filings",
            360,
            "Normal",
            "V1 follows the public filing source you choose rather than querying a paid data feed."),
        Web(
            "policy-public-record",
            "Policy & Public Record Change Monitor",
            "Public Information",
            "Follow a public policy, ordinance, rule, or records page for changes.",
            "Clarity preserves before/after evidence from the public source.",
            "Policy or records page URL",
            "https://example.gov/policies",
            720,
            "Normal",
            "Use the authoritative public source when possible."),
        Web(
            "recall-alert",
            "Recall Alert Monitor",
            "Public Information",
            "Follow a public recall or safety-notice page for changes.",
            "Clarity records the source page and surfaces new or changed recall information with evidence.",
            "Recall or safety page URL",
            "https://example.gov/recalls",
            360,
            "High",
            "Use an official manufacturer, agency, regulator, or other authoritative public recall source."),
        Web(
            "local-government-project",
            "Local Government Project Monitor",
            "Public Information",
            "Follow zoning, permits, road work, development, or project pages.",
            "Clarity preserves changes so new plans, dates, documents, or notices are easier to catch.",
            "Government project page URL",
            "https://example.gov/projects/project-name",
            360,
            "Normal",
            "Best for stable public pages maintained by a city, county, agency, or planning department."),
        Web(
            "school-community-notice",
            "School & Community Notice Monitor",
            "Public Information",
            "Know when a school, district, library, or community notice page changes.",
            "Clarity builds a history of the notice page and surfaces changed public information.",
            "Notice page URL",
            "https://example.edu/notices",
            360,
            "Normal",
            "Useful for calendars, district notices, board information, closures, and policy updates."),
        Web(
            "consumer-notice",
            "Consumer Notice Monitor",
            "Public Information",
            "Follow public settlement, refund, recall, class-action, or consumer notice pages.",
            "Clarity preserves the public notice history and alerts when the source changes.",
            "Consumer notice page URL",
            "https://example.gov/consumer-notices",
            360,
            "Normal",
            "Prefer official regulators, courts, settlement administrators, or manufacturers."),

        Web(
            "brand-mention-source",
            "Brand Mention Source Monitor",
            "Your Identity",
            "Follow a public page, feed, search page, or directory where your brand may be mentioned.",
            "Clarity records changes to the public source so new mention evidence is easier to review.",
            "Public mention source URL",
            "https://example.com/search?q=brand",
            60,
            "Normal",
            "V1 monitors the public source you choose; it is not a universal web-crawling mention index."),
        Uptime(
            "username-impersonation",
            "Username Impersonation Watch",
            "Your Identity",
            "Watch a specific public profile URL for appearance, disappearance, or availability-state changes.",
            "Clarity records whether the public profile URL responds so a suspected account can be followed over time.",
            "Public profile URL",
            "https://example.com/username",
            360,
            "High",
            "V1 watches specific public profiles you identify rather than enumerating every platform automatically."),
        Domain(
            "domain-typosquat",
            "Typo Domain Registration Monitor",
            "Your Identity",
            "Follow a specific lookalike domain and know when its public registration state changes.",
            "Clarity uses public RDAP results so a suspected typo domain can be followed over time.",
            "Lookalike domain",
            "examp1e.com",
            720,
            "High",
            "V1 follows specific domains you provide rather than generating every possible typo automatically."),
        Web(
            "certificate-transparency",
            "Certificate Transparency Domain Monitor",
            "Your Identity",
            "Follow a public certificate-transparency report for domain certificate changes.",
            "Clarity keeps the public report history so new certificate evidence is easier to catch.",
            "Public certificate-transparency report URL",
            "https://crt.sh/?q=%25.example.com",
            360,
            "High",
            "V1 follows the public CT report URL you choose."),
        Web(
            "reputation-change",
            "Reputation Report Monitor",
            "Your Identity",
            "Follow a public reputation, rating, review, or trust report for changes.",
            "Clarity preserves the report-page history so reputation changes remain reviewable.",
            "Public reputation report URL",
            "https://example.com/report",
            720,
            "Normal",
            "V1 monitors the public report source you choose and does not claim a proprietary reputation index."),

        Uptime(
            "api-endpoint-uptime",
            "API Endpoint Uptime Monitor",
            "Reliability",
            "Know when a public API endpoint stops responding or recovers.",
            "Clarity records HTTP availability transitions for the endpoint.",
            "Public API endpoint URL",
            "https://api.example.com/health",
            5,
            "High",
            "Use a safe public health or status endpoint; authenticated/private endpoints are outside V1."),
        Uptime(
            "webhook-health",
            "Webhook Health Endpoint Monitor",
            "Reliability",
            "Watch a public webhook health or status endpoint for availability changes.",
            "Clarity records failure and recovery history for the public health endpoint.",
            "Public webhook health URL",
            "https://example.com/webhooks/health",
            15,
            "High",
            "V1 monitors a public health/status URL rather than sending private synthetic webhook payloads."),
        Uptime(
            "cron-heartbeat",
            "Cron Job Heartbeat Status Monitor",
            "Reliability",
            "Watch a public cron or scheduled-job health endpoint.",
            "Clarity records when the public heartbeat/status endpoint becomes unavailable or recovers.",
            "Public job health URL",
            "https://example.com/jobs/health",
            15,
            "High",
            "V1 observes an existing public heartbeat/status endpoint rather than hosting an inbound heartbeat collector."),
        Uptime(
            "backup-heartbeat",
            "Scheduled Backup Heartbeat Status Monitor",
            "Reliability",
            "Watch a public backup health or heartbeat endpoint.",
            "Clarity records availability and recovery history for the public backup-status endpoint.",
            "Public backup health URL",
            "https://example.com/backups/health",
            60,
            "High",
            "V1 observes an existing public status endpoint rather than receiving backup-agent callbacks."),
        Uptime(
            "email-delivery-heartbeat",
            "Email Delivery Heartbeat Status Monitor",
            "Reliability",
            "Watch a public mail-flow health or heartbeat endpoint.",
            "Clarity records availability changes for the public mail-flow status endpoint.",
            "Public mail health URL",
            "https://example.com/mail/health",
            15,
            "High",
            "V1 observes an existing public health endpoint rather than sending synthetic email probes."),
        Web(
            "cloud-service-outage",
            "Cloud Service Status Monitor",
            "Reliability",
            "Follow a cloud or SaaS provider's public status page for incident changes.",
            "Clarity keeps public status-page history so incident and recovery changes are easier to catch.",
            "Provider status page URL",
            "https://status.example.com",
            15,
            "High",
            "Create one follow per provider or status source you care about.")
    ];

    public IReadOnlyList<ClarityProduct> GetAll() => Products;

    public ClarityProduct? GetBySlug(string? slug) => Products
        .FirstOrDefault(x => string.Equals(
            x.Slug,
            slug,
            StringComparison.OrdinalIgnoreCase));

    private static ClarityProduct Web(
        string slug,
        string name,
        string family,
        string shortDescription,
        string outcome,
        string targetLabel,
        string targetPlaceholder,
        int cadence,
        string importance,
        string helpText) =>
        Create(
            slug,
            name,
            family,
            shortDescription,
            outcome,
            targetLabel,
            targetPlaceholder,
            "WebPage",
            AdapterTypes.Http,
            "{\"mode\":\"content\"}",
            cadence,
            importance,
            helpText);

    private static ClarityProduct Uptime(
        string slug,
        string name,
        string family,
        string shortDescription,
        string outcome,
        string targetLabel,
        string targetPlaceholder,
        int cadence,
        string importance,
        string helpText) =>
        Create(
            slug,
            name,
            family,
            shortDescription,
            outcome,
            targetLabel,
            targetPlaceholder,
            "Website",
            AdapterTypes.Http,
            "{\"mode\":\"uptime\"}",
            cadence,
            importance,
            helpText);

    private static ClarityProduct Tls(
        string slug,
        string name,
        string family,
        string shortDescription,
        string outcome,
        string targetLabel,
        string targetPlaceholder,
        int cadence,
        string importance,
        string helpText) =>
        Create(
            slug,
            name,
            family,
            shortDescription,
            outcome,
            targetLabel,
            targetPlaceholder,
            "TlsEndpoint",
            AdapterTypes.Tls,
            "{}",
            cadence,
            importance,
            helpText);

    private static ClarityProduct Domain(
        string slug,
        string name,
        string family,
        string shortDescription,
        string outcome,
        string targetLabel,
        string targetPlaceholder,
        int cadence,
        string importance,
        string helpText) =>
        Create(
            slug,
            name,
            family,
            shortDescription,
            outcome,
            targetLabel,
            targetPlaceholder,
            "Domain",
            AdapterTypes.Domain,
            "{}",
            cadence,
            importance,
            helpText);

    private static ClarityProduct DnsAddress(
        string slug,
        string name,
        string family,
        string shortDescription,
        string outcome,
        string targetLabel,
        string targetPlaceholder,
        int cadence,
        string importance,
        string helpText) =>
        Create(
            slug,
            name,
            family,
            shortDescription,
            outcome,
            targetLabel,
            targetPlaceholder,
            "DnsRecordSet",
            AdapterTypes.Dns,
            "{}",
            cadence,
            importance,
            helpText);

    private static ClarityProduct DnsRecord(
        string slug,
        string name,
        string family,
        string shortDescription,
        string outcome,
        string targetLabel,
        string targetPlaceholder,
        string recordType,
        int cadence,
        string importance) =>
        Create(
            slug,
            name,
            family,
            shortDescription,
            outcome,
            targetLabel,
            targetPlaceholder,
            "DnsRecordSet",
            AdapterTypes.DnsRecord,
            JsonSerializer.Serialize(new
            {
                recordType
            }),
            cadence,
            importance,
            $"V1 resolves public {recordType} records through a DNS-over-HTTPS source and stores normalized answers as evidence.");

    private static ClarityProduct Create(
        string slug,
        string name,
        string family,
        string shortDescription,
        string outcome,
        string targetLabel,
        string targetPlaceholder,
        string targetType,
        string adapterType,
        string configurationJson,
        int cadence,
        string importance,
        string helpText) =>
        new(
            slug,
            name,
            shortDescription,
            outcome,
            targetLabel,
            targetPlaceholder,
            targetType,
            ToMonitorType(slug),
            adapterType,
            configurationJson,
            cadence,
            importance,
            "AnyMeaningfulChange",
            helpText,
            family);

    private static string ToMonitorType(string slug) =>
        string.Concat(
            slug
                .Split('-', StringSplitOptions.RemoveEmptyEntries)
                .Select(x => char.ToUpperInvariant(x[0]) + x[1..]));
}
