using ClarityBelongs.Web.Domain;

namespace ClarityBelongs.Web.Services;

public sealed record ClarityProduct(
    string Slug,
    string Name,
    string ShortDescription,
    string Outcome,
    string TargetLabel,
    string TargetPlaceholder,
    string TargetType,
    string MonitorType,
    string AdapterType,
    string SourceConfigurationJson,
    int DefaultCadenceMinutes,
    string DefaultImportance,
    string DefaultAlertRule,
    string HelpText,
    string Family = "Your Internet");

public sealed class ClarityProductCatalog
{
    private static readonly IReadOnlyList<ClarityProduct> Products =
    [
        new(
            "website-change",
            "Website Change Monitor",
            "Know when the content of a public webpage changes.",
            "Clarity keeps a history of the page and surfaces meaningful before/after changes.",
            "Webpage URL",
            "https://example.com/pricing",
            "WebPage",
            "WebsiteChange",
            AdapterTypes.Http,
            "{\"mode\":\"content\"}",
            60,
            "Normal",
            "AnyMeaningfulChange",
            "Best for pricing pages, policies, product pages, public notices, and other pages you would otherwise revisit manually."),
        new(
            "website-uptime",
            "Website Uptime Monitor",
            "Know when a website stops responding or recovers.",
            "Clarity watches the HTTP result without treating normal response-time variation as a content change.",
            "Website URL",
            "https://example.com",
            "Website",
            "WebsiteUptime",
            AdapterTypes.Http,
            "{\"mode\":\"uptime\"}",
            5,
            "High",
            "AnyMeaningfulChange",
            "Use this for websites and public endpoints where availability matters."),
        new(
            "ssl-expiration",
            "SSL Expiration Monitor",
            "Track certificate identity and expiration.",
            "Clarity records the current certificate and makes certificate changes visible.",
            "HTTPS site or host",
            "https://example.com",
            "TlsEndpoint",
            "SslExpiration",
            AdapterTypes.Tls,
            "{}",
            720,
            "High",
            "AnyMeaningfulChange",
            "Clarity observes the public TLS certificate presented by the endpoint. Expiration state is included in every snapshot."),
        new(
            "domain-expiration",
            "Domain Expiration Monitor",
            "Track the expiration date published by the domain registry.",
            "Clarity uses RDAP data to keep domain registration expiration visible.",
            "Domain",
            "example.com",
            "Domain",
            "DomainExpiration",
            AdapterTypes.Domain,
            "{}",
            1440,
            "High",
            "AnyMeaningfulChange",
            "Registry data availability varies by TLD. Clarity stores the evidence returned by the RDAP lookup."),
        new(
            "dns-change",
            "DNS Change Monitor",
            "Know when a hostname starts resolving somewhere different.",
            "Clarity stores the normalized public address set and reports changes.",
            "Hostname",
            "example.com",
            "DnsRecordSet",
            "DnsChange",
            AdapterTypes.Dns,
            "{}",
            60,
            "High",
            "AnyMeaningfulChange",
            "V1 observes the public IP address set returned by DNS. More DNS record types can be added without changing the Clarity history model."),
        new(
            "restock-availability",
            "Restock & Availability Monitor",
            "Know when a public product or availability page changes.",
            "Clarity keeps the page history so you can spot restocks, availability changes, or listing updates without checking manually.",
            "Product or availability page URL",
            "https://example.com/product",
            "WebPage",
            "RestockAvailability",
            AdapterTypes.Http,
            "{\"mode\":\"content\"}",
            60,
            "Normal",
            "AnyMeaningfulChange",
            "V1 watches the public page itself. It does not bypass retailer controls or guarantee that every page exposes stock state in its HTML.",
            "Money"),
        new(
            "recall-alert",
            "Recall Alert Monitor",
            "Follow a public recall or safety-notice page for changes.",
            "Clarity records the source page and surfaces new or changed recall information with before/after evidence.",
            "Recall or safety page URL",
            "https://example.gov/recalls",
            "WebPage",
            "RecallAlert",
            AdapterTypes.Http,
            "{\"mode\":\"content\"}",
            360,
            "High",
            "AnyMeaningfulChange",
            "Use an official manufacturer, agency, regulator, or other public recall source that matters to you.",
            "Public Information"),
        new(
            "local-government-project",
            "Local Government Project Monitor",
            "Follow zoning, permits, road work, development, or project pages.",
            "Clarity preserves changes to the public project source so new plans, dates, documents, or notices are easier to catch.",
            "Government project page URL",
            "https://example.gov/projects/project-name",
            "WebPage",
            "LocalGovernmentProject",
            AdapterTypes.Http,
            "{\"mode\":\"content\"}",
            360,
            "Normal",
            "AnyMeaningfulChange",
            "Best for stable public pages maintained by a city, county, agency, planning department, or project office.",
            "Public Information"),
        new(
            "school-community-notice",
            "School & Community Notice Monitor",
            "Know when a school, district, library, or community notice page changes.",
            "Clarity builds a history of the notice page and surfaces new or changed information.",
            "Notice page URL",
            "https://example.edu/notices",
            "WebPage",
            "SchoolCommunityNotice",
            AdapterTypes.Http,
            "{\"mode\":\"content\"}",
            360,
            "Normal",
            "AnyMeaningfulChange",
            "Useful for calendars, district notices, board information, closures, policy notices, and community updates published on public pages.",
            "Public Information"),
        new(
            "fee-change",
            "Fee Change Monitor",
            "Track public pages that publish fees, rates, or charges.",
            "Clarity keeps before/after evidence when the published page changes so you can review what changed over time.",
            "Fee or rate page URL",
            "https://example.com/fees",
            "WebPage",
            "FeeChange",
            AdapterTypes.Http,
            "{\"mode\":\"content\"}",
            720,
            "Normal",
            "AnyMeaningfulChange",
            "Use for banks, utilities, subscriptions, government services, memberships, or other public fee schedules.",
            "Money"),
        new(
            "service-outage",
            "Service Outage Monitor",
            "Know when a public service endpoint stops responding or recovers.",
            "Clarity records availability transitions and recovery history for the public endpoint you follow.",
            "Service or status URL",
            "https://status.example.com",
            "Website",
            "ServiceOutage",
            AdapterTypes.Http,
            "{\"mode\":\"uptime\"}",
            5,
            "High",
            "AnyMeaningfulChange",
            "Use a public status page or endpoint whose HTTP availability is a useful signal. V1 does not infer outages from private account data.",
            "Changes"),
        new(
            "sale-price-history",
            "Price & Sale History Monitor",
            "Keep a change history for a public pricing or product page.",
            "Clarity preserves page snapshots so you can compare current claims, sale language, and published prices with earlier versions.",
            "Pricing or product page URL",
            "https://example.com/product",
            "WebPage",
            "PriceSaleHistory",
            AdapterTypes.Http,
            "{\"mode\":\"content\"}",
            360,
            "Normal",
            "AnyMeaningfulChange",
            "V1 records page changes and evidence rather than promising structured price extraction from every retailer.",
            "Money"),
        new(
            "cancellation-change",
            "Cancellation & Change Monitor",
            "Follow a public schedule, event, travel, appointment, or meeting page for changes.",
            "Clarity records the page history and surfaces changed dates, cancellation notices, or other public updates when the source changes.",
            "Schedule or event page URL",
            "https://example.com/event",
            "WebPage",
            "CancellationChange",
            AdapterTypes.Http,
            "{\"mode\":\"content\"}",
            60,
            "High",
            "AnyMeaningfulChange",
            "Choose the official public page most likely to publish the change you care about.",
            "Changes"),
        new(
            "deadline-change",
            "Deadline Monitor",
            "Follow a public application, registration, benefit, grant, or filing deadline page.",
            "Clarity keeps the source history so newly published or changed deadlines are easier to notice.",
            "Deadline page URL",
            "https://example.gov/deadlines",
            "WebPage",
            "DeadlineChange",
            AdapterTypes.Http,
            "{\"mode\":\"content\"}",
            360,
            "High",
            "AnyMeaningfulChange",
            "Clarity watches the page you choose; always verify important deadlines with the authoritative source before relying on them.",
            "Opportunities"),
        new(
            "consumer-notice",
            "Consumer Notice Monitor",
            "Follow public settlement, refund, recall, class-action, or consumer notice pages.",
            "Clarity preserves the public notice history and alerts when the source changes.",
            "Consumer notice page URL",
            "https://example.gov/consumer-notices",
            "WebPage",
            "ConsumerNotice",
            AdapterTypes.Http,
            "{\"mode\":\"content\"}",
            360,
            "Normal",
            "AnyMeaningfulChange",
            "Best for official regulators, courts, settlement administrators, manufacturers, or other authoritative public notice sources.",
            "Public Information")
    ];

    public IReadOnlyList<ClarityProduct> GetAll() => Products;

    public ClarityProduct? GetBySlug(string? slug) => Products
        .FirstOrDefault(x => string.Equals(x.Slug, slug, StringComparison.OrdinalIgnoreCase));
}
